# Generated by Django 6.1 on 2026-08-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Category',
        ),
    ]
