# Generated by Django 6.1 on 2026-09-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='price_after_discount',
        ),
    ]
